---
- name: Install LEMP Stack Packages
  dnf:
	name:
		- nginx
		- mariadb-server
		- php-fpm
		- php-mysqlnd
	state: present
	update_cache: yes

- name: Enable and start services
  systemd:
  	name: "{{ item }}"
  	state: started
  	enabled: yes
  loop:
  	- nginx
  	- mariadb
  	- php-fpm