---
- name: Install and configure DHCP and DNS on Ubuntu
  hosts: dhcp_dns_servers
  become: true
  vars:
    dhcp_subnet: "192.168.1.0"
    dhcp_netmask: "255.255.255.0"
    dhcp_range_start: "192.168.1.100"
    dhcp_range_end: "192.168.1.200"
    dhcp_router: "192.168.1.1"
    dhcp_broadcast: "192.168.1.255"
    dns_domain: "asa.com"
    dns_forwarders:
      - "8.8.8.8"
      - "1.1.1.1"

  tasks:

  - name: Install DHCP and DNS packages
    apt:
      name:
        - isc-dhcp-server
        - bind9
        - ufw
        - fail2ban
      state: present
      update_cache: yes

  - name: Ensure UFW is enabled and started
    command: ufw enable

  - name: Open DHCP and DNS ports in the firewall
    command: ufw allow "{{ item }}"
    loop:
      - 67/udp  # DHCP
      - 53      # DNS

  - name: Ensure Fail2Ban is running and enabled
    service:
      name: fail2ban
      state: started
      enabled: true

  - name: Configure DHCP server
    copy:
      dest: /etc/dhcp/dhcpd.conf
      content: |
        subnet {{ dhcp_subnet }} netmask {{ dhcp_netmask }} {
          range {{ dhcp_range_start }} {{ dhcp_range_end }}; 
          option routers {{ dhcp_router }};
          option broadcast-address {{ dhcp_broadcast }};
          option domain-name "{{ dns_domain }}";
          option domain-name-servers 127.0.0.1;
        }

  - name: Enable and start DHCP server
    service:
      name: isc-dhcp-server
      enabled: true
      state: started

  - name: Configure BIND DNS server
    blockinfile:
      path: /etc/bind/named.conf.options
      insertafter: 'options {'
      block: |
        listen-on port 53 { any; };
        allow-query { any; };
        recursion yes;
        forwarders {
          {{ dns_forwarders | join("; ") }};
        };

  - name: Ensure named service is enabled and started
    service:
      name: bind9
      enabled: true
      state: started    ---
    - name: Install and configure DHCP and DNS on Ubuntu
      hosts: dhcp_dns_servers
      become: true
      vars:
        dhcp_subnet: "192.168.1.0"
        dhcp_netmask: "255.255.255.0"
        dhcp_range_start: "192.168.1.100"
        dhcp_range_end: "192.168.1.200"
        dhcp_router: "192.168.1.1"
        dhcp_broadcast: "192.168.1.255"
        dns_domain: "asa.com"
        dns_forwarders:
          - "8.8.8.8"
          - "1.1.1.1"
    
      tasks:
    
      - name: Install DHCP and DNS packages
        apt:
          name:
            - isc-dhcp-server
            - bind9
            - ufw
            - fail2ban
          state: present
          update_cache: yes
    
      - name: Ensure UFW is enabled and started
        command: ufw enable
    
      - name: Open DHCP and DNS ports in the firewall
        command: ufw allow "{{ item }}"
        loop:
          - 67/udp  # DHCP
          - 53      # DNS
    
      - name: Ensure Fail2Ban is running and enabled
        service:
          name: fail2ban
          state: started
          enabled: true
    
      - name: Configure DHCP server
        copy:
          dest: /etc/dhcp/dhcpd.conf
          content: |
            subnet {{ dhcp_subnet }} netmask {{ dhcp_netmask }} {
              range {{ dhcp_range_start }} {{ dhcp_range_end }}; 
              option routers {{ dhcp_router }};
              option broadcast-address {{ dhcp_broadcast }};
              option domain-name "{{ dns_domain }}";
              option domain-name-servers 127.0.0.1;
            }
    
      - name: Enable and start DHCP server
        service:
          name: isc-dhcp-server
          enabled: true
          state: started
    
      - name: Configure BIND DNS server
        blockinfile:
          path: /etc/bind/named.conf.options
          insertafter: 'options {'
          block: |
            listen-on port 53 { any; };
            allow-query { any; };
            recursion yes;
            forwarders {
              {{ dns_forwarders | join("; ") }};
            };
    
      - name: Ensure named service is enabled and started
        service:
          name: bind9
          enabled: true
          state: started