---
- name: Install and configure DHCP and DNS on Rocky Linux 9
  hosts: dhcp_dns_servers
  become: true
  tasks:

  - name: Install DHCP and DNS packages
    dnf:
      name:
        - dhcp-server
        - bind
        - firewalld
        - fail2ban
      state: present

  - name: Ensure firewalld is running and enabled
    service:
      name: firewalld
      state: started
      enabled: true

  - name: Ensure Fail2Ban is running and enabled
    service:
      name: fail2ban
      state: started
      enabled: true

  - name: Open DHCP and DNS ports in the firewall
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
      immediate: yes
    loop:
      - dhcp
      - dns

  - name: Configure DHCP server
    copy:
      dest: /etc/dhcp/dhcpd.conf
      content: |
        subnet {{ dhcp_subnet }} netmask {{ dhcp_netmask }} {
          range {{ dhcp_range_start }} {{ dhcp_range_end }};
          option routers {{ dhcp_router }};
          option broadcast-address {{ dhcp_broadcast }};
          option domain-name "{{ dns_domain }}";
          option domain-name-servers 127.0.0.1;
        }

  - name: Enable and start DHCP server
    service:
      name: dhcpd
      enabled: true
      state: started

  - name: Configure BIND DNS server
    blockinfile:
      path: /etc/named.conf
      insertafter: 'options {'
      block: |
        listen-on port 53 { any; };
        allow-query { any; };
        recursion yes;
        forwarders {
          {{ dns_forwarders | join("; ") }};
        };

  - name: Ensure named service is enabled and started
    service:
      name: named
      enabled: true
      state: started
